### ISSUE TITLE
facial landmark to facial expressions like eye closure 

### ISSUE THREAD

**Issue by sunit1409** [gimyboya/real-imoji#1]
Hi @gimyboya ,
Can you please help me understand the algorithms used to map facial landmarks that has been detected to various advanced expressions like jaw drop , lip press , mouth open etc.

**Comment by khawarizmus** [comment]
Hello there @sunit1409 !

This spa uses [Affectiva SDK](https://www.affectiva.com/product/emotion-sdk/) under the hood.
The internal details of how the SDK works are unknown to me. However, I would be interested to know more if you happen to get something interesting to share here.

Thank you for your question :)

**Comment by khawarizmus** [comment]
BTW if you are wondering where I am including the SDK it's [here](https://github.com/gimyboya/Real-emoji/blob/master/public/index.html#L11)
